[package]
name = "rust_graph"
version = "0.1.9"
authors = ["Zhengyi Yang <zhengyi.yang@outlook.com>"]
autoexamples = true

[features]
default = []
usize_id = []
ldbc = []

[dependencies]
indexmap = { version = "1.0.2",features = ["serde-1"] }
memmap="0.7.0"
serde = "1.0.80"
serde_derive = "1.0.80"
rand = "0.5.5"
itertools = "0.7.8"
bincode = "1.0.1"
log = "0.4"
csv = "1"
counter = "0.4.3"
regex = "1"
seahash = "3.0.5"
fnv = "1.0.6"
json = "0.11.13"
sled = "0.17.4"
fixedbitset = { git = "https://github.com/vks/fixedbitset", branch = "faster-iter" }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.0.4"
pbr = "1.0.1"
clap = "2.32.0"
criterion = "0.2"


[[example]]
name = "ldbc_to_graphmap"
required-features = ["ldbc"]

