[package]
name = "rust_graph"
version = "0.1.9"
authors = ["Zhengyi Yang <zhengyi.yang@outlook.com>"]
edition = "2018"
autoexamples = true

[features]
default = []
usize_id = []
#pre_fetch = ["threadpool"]
local_degree = []

[dependencies]
indexmap = { version = "1.0.2",features = ["serde-1"] }
memmap="0.7.0"
serde = "1.0.80"
serde_derive = "1.0.80"
rand = "0.5.5"
itertools = "0.7.8"
bincode = "1.0.1"
log = "0.4"
csv = "1"
counter = "0.4.3"
fixedbitset = "0.1.9"
hashbrown = {version = "0.2.0", features = ["serde"] }
rayon = "1.0.3"
serde_json = "1.0.39"
fxhash = "0.2.1"
#cdrs = "2.1.0"
#cdrs_helpers_derive = "0.3.0"
lru = "0.1.17"
futures = "0.3.1"
tarpc= {version = "0.20.0", features = ["full"]}
tokio = { version = "0.2.4", features = ["full"] }
tokio-serde = {version="0.6.0", features = ["bincode"]}
parking_lot = "0.9.0"
read_line = "0.0.1"
byte-unit = "3.0.3"
#crossbeam-channel = "0.4.0"
#threadpool = { version = "1.7.1", optional = true }

[dev-dependencies]
tempfile = "3.0.4"
clap = "2.32.0"
