[package]
name = "rust_graph"
version = "0.1.9"
authors = ["Zhengyi Yang <zhengyi.yang@outlook.com>"]
autoexamples = true

[features]
default = []
usize_id = []

[dependencies]
indexmap = { version = "1.0.2",features = ["serde-1"] }
memmap="0.7.0"
serde = "1.0.80"
serde_derive = "1.0.80"
rand = "0.5.5"
itertools = "0.7.8"
bincode = "1.0.1"
log = "0.4"
csv = "1"
counter = "0.4.3"
serde_cbor = "0.9.0"
fixedbitset = "0.1.9"
hashbrown = {version = "0.2.0", features = ["serde"] }
rayon = "1.0.3"
serde_json = "1.0.39"
fxhash = "0.2.1"
rocksdb = "0.12.2"
lru = "0.1.15"
scoped_threadpool = "0.1.9"

[dependencies.hdfs]
git="https://github.com/UNSW-database/hdfs-rs.git"

[dev-dependencies]
tempfile = "3.0.4"
clap = "2.32.0"
criterion = "0.2"
tempdir = "0.3.7"