[package]
name = "rust_graph"
version = "0.1.9"
authors = ["Zhengyi Yang <zhengyi.yang@outlook.com>"]
edition = "2018"
autoexamples = true

[features]
default = []
usize_id = []

[dependencies]
indexmap = { version = "1.0.2",features = ["serde-1"] }
memmap="0.7.0"
serde = "1.0.80"
serde_derive = "1.0.80"
rand = "0.5.5"
itertools = "0.7.8"
bincode = "1.0.1"
log = "0.4"
csv = "1"
counter = "0.4.3"
fixedbitset = "0.1.9"
hashbrown = {version = "0.2.0", features = ["serde"] }
rayon = "1.0.3"
serde_json = "1.0.39"
fxhash = "0.2.1"
cdrs = "2.1.0"
cdrs_helpers_derive = "0.3.0"
lru = "0.1.17"
tarpc= {git="https://github.com/google/tarpc.git", features=["serde1"]}
tarpc-bincode-transport = {git="https://github.com/google/tarpc.git"}
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
tokio = "0.2.0-alpha.1"
parking_lot = "0.9.0"
read_line = "0.0.1"

[dev-dependencies]
tempfile = "3.0.4"
clap = "2.32.0"
