[package]
name = "rust_graph"
version = "0.1.0"
authors = ["Zhengyi Yang <zhengyi.yang@outlook.com>"]

[dependencies]
indexmap = { version = "1.0.1",features = ["serde-1"] }
serde = "1.0.55"
serde_derive = "1.0.55"
rand="0.4.2"
itertools="0.7.8"