[package]
name = "rust_graph"
version = "0.1.5"
authors = ["Zhengyi Yang <zhengyi.yang@outlook.com>"]

[features]
default=[]
usize_id=[]

[dependencies]
indexmap = { version = "1.0.1",features = ["serde-1"] }
serde = "1.0.55"
serde_derive = "1.0.55"
rand="0.4.2"
itertools="0.7.8"
bincode = "0.8"
log = "0.4"
csv = "1"
regex="1"