[package]
name = "rust_graph"
version = "0.1.0"
authors = ["Zhengyi Yang <zhengyi.yang@outlook.com>"]

[dependencies]
rand="*"
indexmap = { version = "*",features = ["serde-1"] }
serde = "*"
serde_derive = "*"