[package]
name = "rust_graph"
version = "0.1.9"
authors = ["Zhengyi Yang <zhengyi.yang@outlook.com>"]
edition = "2018"
autoexamples = true

[features]
default = []
usize_id = []

[dependencies]
indexmap = { version = "1.3.2",features = ["serde-1"] }
serde = "1.0.106"
serde_derive = "1.0.106"
rand = "0.7.3"
itertools = "0.9.0"
bincode = "1.2.1"
log = "0.4"
csv = "1"
counter = "0.4.3"
fixedbitset = "0.2.0"
hashbrown = { version = "0.7.1", features = ["rayon","serde"] }
rayon = "1.3.0"
serde_json = "1.0.51"
fxhash = "0.2.1"

[dev-dependencies]
tempfile = "3.0.4"
