[package]
name = "rust_graph"
version = "0.1.8"
authors = ["Zhengyi Yang <zhengyi.yang@outlook.com>"]

[features]
default = []
usize_id = []
ldbc = ["regex"]

[dependencies]
indexmap = { version = "1.0.2",features = ["serde-1"] }
memmap="0.7.0"
serde = "1.0.80"
serde_derive = "1.0.80"
rand = "0.5.5"
itertools = "0.7.8"
bincode = "1.0.1"
log = "0.4"
csv = "1"
counter = "0.4.3"
regex = {version = "1", optional = true }
fnv = "1.0.6"

[dev-dependencies]
tempfile = "3.0.4"
pbr = "1.0.1"
clap = "2.32.0"
time = "0.1.40"

[[example]]
name = "ldbc_to_graphmap"
required-features = ["ldbc"]

[[example]]
name = "csv_to_static"

[[example]]
name = "static_to_csv"

[[example]]
name = "static_to_mmap"

[[example]]
name = "stats"



